// Run against a disposable local DATABASE_PATH. Never seed a live public service.
const { chromium } = require('playwright');
const fs = require('node:fs');
const path = require('node:path');
const assert = require('node:assert/strict');
const base = 'http://127.0.0.1:8010';
const out = path.resolve('test-artifacts');
const stamp = Date.now().toString(36);

(async () => {
  const browser = await chromium.launch({headless:true, executablePath:process.env.CHROME_PATH || 'C:/Program Files/Google/Chrome/Application/chrome.exe'});
  const errors=[];
  async function user(name) {
    const context=await browser.newContext({viewport:{width:1440,height:1000}});
    const page=await context.newPage();
    page.on('pageerror',e=>errors.push(e.message));
    await page.goto(base+'/login');
    await page.getByText('처음이라면 계정 만들기',{exact:true}).click();
    const form=page.locator('form[action="/register"]');
    await form.locator('[name=name]').fill(name);
    await form.locator('[name=handle]').fill(name+'_'+stamp);
    await form.locator('[name=password]').fill('browser-test-'+stamp);
    await form.getByRole('button').click();
    await page.waitForURL(base+'/', {timeout:10000}).catch(async error => {
      console.log('Registration failed at',page.url(),await page.locator('body').innerText());
      throw error;
    });
    return page;
  }
  const a=await user('asker'), b=await user('expert'), c=await user('reader');
  await a.goto(base+'/new');
  await a.locator('[name=title]').fill('세 사람의 경험이 이어지는 브라우저 검증');
  await a.locator('[name=body]').fill('교대 근무에서 인수인계 누락을 줄이려면 어떻게 해야 하나요?');
  await a.locator('[name=conditions]').fill('세 명이 교대하는 작은 팀');
  await a.getByRole('button',{name:'질문 남기기'}).click();
  await a.waitForURL('**/questions/*');
  const url=a.url();
  await b.goto(url);
  const answer=b.locator('#answer-form form');
  await answer.locator('[name=body]').fill('저희 팀에서는 다음 사람이 확인할 항목 세 가지를 남기고 출근 시 읽었다고 표시했습니다.');
  await answer.locator('[name=conditions]').fill('같은 업무를 세 명이 이어받을 때');
  await answer.locator('[name=evidence]').fill('직접 운영하며 관찰한 사례');
  await answer.getByRole('button',{name:'내 이름으로 답변 남기기'}).click();
  await b.waitForURL('**#r-*');
  await a.goto(url);
  await a.getByRole('button',{name:'이 답이 도움됐어요'}).click();
  await a.waitForURL('**#r-*');
  await a.getByText('직접 써 보고 결과 남기기',{exact:false}).click();
  const outcome=a.locator('form[action$="/outcome"]');
  await outcome.locator('[name=conditions]').fill('우리 팀의 야간 교대');
  await outcome.locator('[name=body]').fill('확인하지 않은 인수인계 항목을 발견할 수 있었습니다.');
  await outcome.locator('[name=observed_at]').fill('2026-01-01');
  await outcome.getByRole('button').click();
  await a.waitForURL('**#r-*');
  await c.goto(base+'/?q='+encodeURIComponent('교대'));
  await c.getByRole('link',{name:'세 사람의 경험이 이어지는 브라우저 검증'}).click();
  await c.getByText('다른 사람이 이어 쓴 기록',{exact:false}).click();
  const reuse=c.locator('form[action$="/reuse"]');
  await reuse.locator('[name=note]').fill('우리 봉사 모임 인수인계에도 참고하려고 합니다.');
  await reuse.getByRole('button').click();
  await c.waitForURL('**#r-*');
  await c.getByRole('link',{name:'이 답에서 이어 묻기'}).click();
  assert.match(await c.locator('body').innerText(),/expert/);
  await c.locator('[name=title]').fill('봉사 모임은 교대 주기가 긴데 어떻게 적용할까요?');
  await c.locator('[name=body]').fill('앞선 사례의 인수인계 방법을 참고했지만 매주 참여자가 달라집니다.');
  await c.getByRole('button',{name:'질문 남기기'}).click();
  await c.waitForURL('**/questions/*');
  assert.match(await c.locator('body').innerText(),/이 길이 시작된 곳/);
  await a.goto(url);
  await a.screenshot({path:path.join(out,'journey-desktop.png'),fullPage:true});
  await a.setViewportSize({width:390,height:844});
  assert.equal(await a.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
  await a.screenshot({path:path.join(out,'journey-mobile.png'),fullPage:true});
  await b.goto(base+'/me');
  assert.match(await b.locator('body').innerText(),/1명/);
  assert.deepEqual(errors,[]);
  fs.writeFileSync(path.join(out,'browser-results.json'),JSON.stringify({passed:true,scenario:'A asks → B answers → A chooses and applies → C searches, reuses and follows up',desktop:1440,mobile:390,pageErrors:errors},null,2));
  console.log('PASS: three-user browser journey, immutable attribution, desktop/mobile, no page errors');
  await browser.close();
})().catch(error=>{console.error(error);process.exit(1)});
